apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        agentpool: nodepool2
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: userdata
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: userdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-csi-premium-v2"
      resources:
        requests:
          storage: 40Gi
