apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-db-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: lab-0
  storageClassName: managed-csi-premium-v2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-db-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: lab-1
  storageClassName: managed-csi-premium-v2
